# Site settings
title: Hello, The Internet
email: AndrewGardhouse@gmail.com
description: Andrew Gardhouse, Full-Stack Web Developer In Sunny Vancouver, BC
keywords: Andrew Gardhouse, Vancouver, BC, British Colombia, Web Developer, Web, Developer, Developers, Javascript, Rails, Ruby, HTML, CSS
baseurl: "" # the subpath of your site, e.g. /blog/ 
github_username:  AndrewGardhouse

# Build settings
markdown: kramdown

gems: [jekyll-sitemap]