# Site settings
title: Hello, The Internet
email: AndrewGardhouse@gmail.com
description: Andrew Gardhouse, freelance jr. full-stack web developer.
baseurl: "" # the subpath of your site, e.g. /blog/ 
github_username:  AndrewGardhouse

# Build settings
markdown: kramdown
