# Site settings
title: Hello, The Internet
email: AndrewGardhouse@gmail.com
description: Andrew Gardhouse, Full-Stack Web Developer
baseurl: "" # the subpath of your site, e.g. /blog/ 
github_username:  AndrewGardhouse

# Build settings
markdown: kramdown
